version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis

volumes:
  redis_data: